import type { Idiom } from '@/types';

// Idioms & strong collocations. Generated content.
export const IDIOMS: Idiom[] = [
  {
    id: 'id-make-a-decision',
    phrase: 'make a decision',
    meaning: 'to decide on something after thinking about it',
    example: 'We need to make a decision about the venue before Friday.',
    level: 'B1',
    kind: 'collocation',
  },
  {
    id: 'id-take-responsibility',
    phrase: 'take responsibility',
    meaning: 'to accept that you are accountable for something',
    example: 'She took responsibility for the mistake and apologised to the team.',
    level: 'B1',
    kind: 'collocation',
  },
  {
    id: 'id-heavy-rain-traffic',
    phrase: 'heavy rain / heavy traffic',
    meaning: 'a large amount of rain, or very congested roads',
    example: 'We were late because of heavy traffic and heavy rain on the motorway.',
    level: 'B1',
    kind: 'collocation',
  },
  {
    id: 'id-strong-coffee-accent',
    phrase: 'strong coffee / strong accent',
    meaning: 'coffee with intense flavour, or a very noticeable accent',
    example: 'He ordered a strong coffee and spoke with a strong Scottish accent.',
    level: 'B1',
    kind: 'collocation',
  },
  {
    id: 'id-do-your-best',
    phrase: 'do your best',
    meaning: 'to try as hard as you can',
    example: "Just do your best in the exam and don't worry about the rest.",
    level: 'B1',
    kind: 'collocation',
  },
  {
    id: 'id-make-an-effort',
    phrase: 'make an effort',
    meaning: 'to try hard to do something',
    example: 'You should make an effort to speak English every day.',
    level: 'B1',
    kind: 'collocation',
  },
  {
    id: 'id-pay-attention',
    phrase: 'pay attention',
    meaning: 'to listen or watch carefully',
    example: 'Please pay attention to the instructions before you start.',
    level: 'B1',
    kind: 'collocation',
  },
  {
    id: 'id-keep-in-touch',
    phrase: 'keep in touch',
    meaning: 'to stay in contact with someone',
    example: "Let's keep in touch after the course finishes.",
    level: 'B1',
    kind: 'collocation',
  },
  {
    id: 'id-meet-a-deadline',
    phrase: 'meet a deadline',
    meaning: 'to finish something by the required time',
    example: 'The team worked late to meet the deadline.',
    level: 'B2',
    kind: 'collocation',
  },
  {
    id: 'id-draw-reach-a-conclusion',
    phrase: 'draw / reach a conclusion',
    meaning: 'to form an opinion or decision after considering the facts',
    example: 'After reviewing the data, we reached the conclusion that the plan had failed.',
    level: 'B2',
    kind: 'collocation',
  },
  {
    id: 'id-raise-awareness',
    phrase: 'raise awareness',
    meaning: 'to make more people know about an issue',
    example: 'The campaign aims to raise awareness about climate change.',
    level: 'B2',
    kind: 'collocation',
  },
  {
    id: 'id-take-for-granted',
    phrase: 'take for granted',
    meaning: 'to fail to appreciate something or assume it will always be there',
    example: 'We often take clean water for granted.',
    level: 'B2',
    kind: 'collocation',
  },
  {
    id: 'id-take-a-risk',
    phrase: 'take a risk',
    meaning: 'to do something that might have a bad outcome',
    example: 'Starting your own business means taking a risk.',
    level: 'B1',
    kind: 'collocation',
  },
  {
    id: 'id-make-progress',
    phrase: 'make progress',
    meaning: 'to improve or move forward',
    example: "You've made great progress with your pronunciation.",
    level: 'B1',
    kind: 'collocation',
  },
  {
    id: 'id-bear-in-mind',
    phrase: 'bear in mind',
    meaning: 'to remember and consider something',
    example: 'Bear in mind that the office is closed on Mondays.',
    level: 'B2',
    kind: 'collocation',
  },
  {
    id: 'id-run-late',
    phrase: 'run late',
    meaning: 'to be behind schedule',
    example: "Sorry, I'm running late, I'll be there in ten minutes.",
    level: 'B1',
    kind: 'collocation',
  },
  {
    id: 'id-break-the-ice',
    phrase: 'break the ice',
    meaning: 'to do or say something to ease tension in a social situation',
    example: 'He told a joke to break the ice at the meeting.',
    level: 'B1',
    kind: 'idiom',
  },
  {
    id: 'id-a-piece-of-cake',
    phrase: 'a piece of cake',
    meaning: 'something very easy to do',
    example: 'The test was a piece of cake; I finished in ten minutes.',
    level: 'B1',
    kind: 'idiom',
  },
  {
    id: 'id-once-in-a-blue-moon',
    phrase: 'once in a blue moon',
    meaning: 'very rarely',
    example: 'We only go to the cinema once in a blue moon.',
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-hit-the-nail-on-the-head',
    phrase: 'hit the nail on the head',
    meaning: 'to describe exactly what is causing a situation or problem',
    example: "You hit the nail on the head; that's exactly the problem.",
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-under-the-weather',
    phrase: 'under the weather',
    meaning: 'feeling slightly ill',
    example: "I'm feeling a bit under the weather, so I'll stay home today.",
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-the-ball-is-in-your-court',
    phrase: 'the ball is in your court',
    meaning: 'it is now your turn to take action or make a decision',
    example: "I've made my offer, so now the ball is in your court.",
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-bite-the-bullet',
    phrase: 'bite the bullet',
    meaning: 'to force yourself to do something difficult or unpleasant',
    example: 'I finally bit the bullet and went to the dentist.',
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-cost-an-arm-and-a-leg',
    phrase: 'cost an arm and a leg',
    meaning: 'to be very expensive',
    example: 'That designer bag cost an arm and a leg.',
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-let-the-cat-out-of-the-bag',
    phrase: 'let the cat out of the bag',
    meaning: 'to reveal a secret, often by accident',
    example: 'She let the cat out of the bag about the surprise party.',
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-get-cold-feet',
    phrase: 'get cold feet',
    meaning: 'to become nervous and hesitant about doing something planned',
    example: 'He got cold feet just before the wedding.',
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-pull-someones-leg',
    phrase: "pull someone's leg",
    meaning: 'to joke with someone by telling them something untrue',
    example: "Relax, I'm just pulling your leg, you didn't really fail.",
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-miss-the-boat',
    phrase: 'miss the boat',
    meaning: 'to miss an opportunity by being too slow',
    example: "If you don't buy now, you'll miss the boat on these prices.",
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-on-the-same-page',
    phrase: 'on the same page',
    meaning: 'to be in agreement or have the same understanding',
    example: "Let's have a quick meeting to make sure we're all on the same page.",
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-cut-corners',
    phrase: 'cut corners',
    meaning: 'to do something cheaply or quickly, sacrificing quality',
    example: 'They cut corners during construction, and now the roof leaks.',
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-a-blessing-in-disguise',
    phrase: 'a blessing in disguise',
    meaning: 'something that seems bad at first but turns out to be good',
    example: 'Losing that job was a blessing in disguise; I found a better one.',
    level: 'C1',
    kind: 'idiom',
  },
  {
    id: 'id-speak-your-mind',
    phrase: 'speak your mind',
    meaning: 'to say what you really think openly',
    example: "She's not afraid to speak her mind in meetings.",
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-go-the-extra-mile',
    phrase: 'go the extra mile',
    meaning: 'to make more effort than is expected',
    example: 'Our staff always go the extra mile to help customers.',
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-beat-around-the-bush',
    phrase: 'beat around the bush',
    meaning: 'to avoid talking about something directly',
    example: 'Stop beating around the bush and tell me what happened.',
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-back-to-square-one',
    phrase: 'back to square one',
    meaning: 'to return to the starting point after a failure',
    example: "The deal fell through, so we're back to square one.",
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-in-the-long-run',
    phrase: 'in the long run',
    meaning: 'over a long period of time in the future',
    example: 'Eating well will save you money in the long run.',
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-the-bottom-line',
    phrase: 'the bottom line',
    meaning: 'the most important fact or the final result',
    example: "The bottom line is that we can't afford this project.",
    level: 'C1',
    kind: 'idiom',
  },
  {
    id: 'id-food-for-thought',
    phrase: 'food for thought',
    meaning: 'something worth thinking about seriously',
    example: 'Her speech gave us a lot of food for thought.',
    level: 'C1',
    kind: 'idiom',
  },
  {
    id: 'id-make-ends-meet',
    phrase: 'make ends meet',
    meaning: 'to earn just enough money to live on',
    example: "With two kids, it's hard to make ends meet on one salary.",
    level: 'C1',
    kind: 'idiom',
  },
  {
    id: 'id-jump-to-conclusions',
    phrase: 'jump to conclusions',
    meaning: 'to form an opinion before knowing all the facts',
    example: "Don't jump to conclusions before you hear his side of the story.",
    level: 'B2',
    kind: 'idiom',
  },
  {
    id: 'id-see-eye-to-eye',
    phrase: 'see eye to eye',
    meaning: 'to agree with someone',
    example: "My brother and I don't always see eye to eye on politics.",
    level: 'C1',
    kind: 'idiom',
  },
  {
    id: 'id-call-it-a-day',
    phrase: 'call it a day',
    meaning: 'to stop working on something for the day',
    example: "We've done enough, let's call it a day.",
    level: 'B2',
    kind: 'idiom',
  },
];
