import type { SoundLesson } from '../types';

// The pronunciation lab: phonemes that matter, with how-to instructions, a note on
// why each is hard for Spanish speakers, example words, and minimal pairs to drill
// discrimination (HVPT-style). All audio is generated by the browser at runtime.

export const SOUNDS: SoundLesson[] = [
  {
    id: 'snd-iy',
    symbol: '/ɪ/ vs /iː/',
    name: 'short i vs long ee (ship / sheep)',
    level: 'A1',
    howTo:
      'For /ɪ/ (ship), relax your mouth and make the sound short. For /iː/ (sheep), spread your lips into a smile and hold it longer.',
    spanishNote:
      'Spanish has only one "i" sound, so ship and sheep sound identical. Train your ear: /ɪ/ is shorter and more relaxed; /iː/ is longer and tenser.',
    examples: ['ship', 'sheep', 'live', 'leave', 'bit', 'beat'],
    pairs: [
      { a: 'ship', b: 'sheep', ipaA: '/ʃɪp/', ipaB: '/ʃiːp/' },
      { a: 'live', b: 'leave', ipaA: '/lɪv/', ipaB: '/liːv/' },
      { a: 'bit', b: 'beat', ipaA: '/bɪt/', ipaB: '/biːt/' },
    ],
  },
  {
    id: 'snd-bv',
    symbol: '/b/ vs /v/',
    name: 'b vs v (berry / very)',
    level: 'A1',
    howTo:
      'For /b/, press both lips together and release. For /v/, put your top teeth gently on your bottom lip and let the air buzz through.',
    spanishNote:
      'In Spanish, b and v are pronounced the same. In English they are different — /v/ uses teeth on lip, never two lips.',
    examples: ['berry', 'very', 'ban', 'van', 'best', 'vest'],
    pairs: [
      { a: 'berry', b: 'very', ipaA: '/ˈberi/', ipaB: '/ˈveri/' },
      { a: 'ban', b: 'van', ipaA: '/bæn/', ipaB: '/væn/' },
      { a: 'bet', b: 'vet', ipaA: '/bet/', ipaB: '/vet/' },
    ],
  },
  {
    id: 'snd-th',
    symbol: '/θ/ vs /t/, /s/',
    name: 'the th sound (think / sink / tink)',
    level: 'A2',
    howTo:
      'Put the tip of your tongue lightly between your teeth and blow air out. For voiced /ð/ (this), add your voice.',
    spanishNote:
      'European Spanish has /θ/ (as in "cielo"), but many learners replace it with /s/ or /t/. Keep the tongue between the teeth.',
    examples: ['think', 'three', 'this', 'that', 'mouth', 'weather'],
    pairs: [
      { a: 'think', b: 'sink', ipaA: '/θɪŋk/', ipaB: '/sɪŋk/' },
      { a: 'thin', b: 'tin', ipaA: '/θɪn/', ipaB: '/tɪn/' },
      { a: 'thanks', b: 'tanks', ipaA: '/θæŋks/', ipaB: '/tæŋks/' },
    ],
  },
];
