import type { SoundLesson } from '@/types';

// Pronunciation lab: phonemes & minimal pairs. Generated content.
export const SOUNDS: SoundLesson[] = [
  {
    id: 'snd-v-ih-ee',
    symbol: '/ɪ/ vs /iː/',
    name: 'short i vs long ee (ship/sheep)',
    level: 'A2',
    howTo:
      'For /ɪ/ keep the tongue high but relaxed and slightly lower and more central, jaw a touch open, lips loose - it is a short, lax sound. For /iː/ push the tongue high and forward toward the front teeth, spread the lips into a smile, and hold it longer with tense muscles.',
    examples: ['ship', 'sheep', 'bit', 'beat', 'fill', 'feel', 'live', 'leave'],
    pairs: [
      {
        a: 'ship',
        b: 'sheep',
        ipaA: '/ʃɪp/',
        ipaB: '/ʃiːp/',
      },
      {
        a: 'bit',
        b: 'beat',
        ipaA: '/bɪt/',
        ipaB: '/biːt/',
      },
      {
        a: 'live',
        b: 'leave',
        ipaA: '/lɪv/',
        ipaB: '/liːv/',
        note: "verb 'live' vs 'leave'",
      },
      {
        a: 'fill',
        b: 'feel',
        ipaA: '/fɪl/',
        ipaB: '/fiːl/',
      },
    ],
  },
  {
    id: 'snd-v-e-ae',
    symbol: '/e/ vs /æ/',
    name: 'short e vs flat a (bet/bat)',
    level: 'A2',
    howTo:
      "For /e/ the jaw is only slightly open and the tongue is mid-front, like the vowel in **bed**. For /æ/ drop the jaw much lower, spread the lips wide and flatten the tongue forward and low - it is an open, bright sound almost like a sheep's 'baa'.",
    examples: ['bet', 'bat', 'men', 'man', 'pen', 'pan', 'said', 'sad'],
    pairs: [
      {
        a: 'bet',
        b: 'bat',
        ipaA: '/bet/',
        ipaB: '/bæt/',
      },
      {
        a: 'men',
        b: 'man',
        ipaA: '/men/',
        ipaB: '/mæn/',
      },
      {
        a: 'pen',
        b: 'pan',
        ipaA: '/pen/',
        ipaB: '/pæn/',
      },
      {
        a: 'said',
        b: 'sad',
        ipaA: '/sed/',
        ipaB: '/sæd/',
      },
    ],
  },
  {
    id: 'snd-v-ae-uh',
    symbol: '/æ/ vs /ʌ/',
    name: 'flat a vs short u (cat/cut)',
    level: 'B1',
    howTo:
      "For /æ/ keep the tongue low and forward with lips spread wide and jaw dropped. For /ʌ/ pull the tongue back to a central, relaxed position with the mouth only moderately open and lips neutral - it is a short, quick 'uh' produced in the middle of the mouth.",
    examples: ['cat', 'cut', 'bat', 'but', 'ran', 'run', 'cap', 'cup'],
    pairs: [
      {
        a: 'cat',
        b: 'cut',
        ipaA: '/kæt/',
        ipaB: '/kʌt/',
      },
      {
        a: 'bat',
        b: 'but',
        ipaA: '/bæt/',
        ipaB: '/bʌt/',
      },
      {
        a: 'ran',
        b: 'run',
        ipaA: '/ræn/',
        ipaB: '/rʌn/',
      },
      {
        a: 'cap',
        b: 'cup',
        ipaA: '/kæp/',
        ipaB: '/kʌp/',
      },
    ],
  },
  {
    id: 'snd-v-uu-oo',
    symbol: '/ʊ/ vs /uː/',
    name: 'short oo vs long oo (full/fool)',
    level: 'A2',
    howTo:
      'For /ʊ/ round the lips loosely with the tongue high and back but relaxed - a short, lax sound. For /uː/ round the lips tightly into a small circle, push the tongue high and far back, and hold the sound longer with tense muscles.',
    examples: ['full', 'fool', 'pull', 'pool', 'look', 'Luke', 'could', 'cooed'],
    pairs: [
      {
        a: 'full',
        b: 'fool',
        ipaA: '/fʊl/',
        ipaB: '/fuːl/',
      },
      {
        a: 'pull',
        b: 'pool',
        ipaA: '/pʊl/',
        ipaB: '/puːl/',
      },
      {
        a: 'look',
        b: 'Luke',
        ipaA: '/lʊk/',
        ipaB: '/luːk/',
      },
      {
        a: 'should',
        b: 'shooed',
        ipaA: '/ʃʊd/',
        ipaB: '/ʃuːd/',
      },
    ],
  },
  {
    id: 'snd-v-oh-uh',
    symbol: '/ɒ/ vs /ʌ/',
    name: 'short o vs short u (cot/cut)',
    level: 'B1',
    howTo:
      "For /ɒ/ (British) drop the jaw and round the lips a little with the tongue low and back - an open, rounded 'o'. In American English this is often /ɑː/, an unrounded open back vowel. For /ʌ/ keep the lips neutral and unrounded with the tongue central and the mouth only moderately open - a short 'uh'.",
    examples: ['cot', 'cut', 'not', 'nut', 'lock', 'luck', 'fond', 'fund'],
    pairs: [
      {
        a: 'cot',
        b: 'cut',
        ipaA: '/kɒt/',
        ipaB: '/kʌt/',
      },
      {
        a: 'not',
        b: 'nut',
        ipaA: '/nɒt/',
        ipaB: '/nʌt/',
      },
      {
        a: 'lock',
        b: 'luck',
        ipaA: '/lɒk/',
        ipaB: '/lʌk/',
      },
      {
        a: 'fond',
        b: 'fund',
        ipaA: '/fɒnd/',
        ipaB: '/fʌnd/',
      },
    ],
  },
  {
    id: 'snd-v-ah-uh',
    symbol: '/ɑː/ vs /ʌ/',
    name: 'long ah vs short u (cart/cut)',
    level: 'B1',
    howTo:
      "For /ɑː/ open the mouth wide, pull the tongue low and back, keep the lips unrounded, and hold the sound long - a deep, open 'aah'. For /ʌ/ keep the mouth only moderately open with the tongue central and the sound short and clipped.",
    examples: ['cart', 'cut', 'heart', 'hut', 'bath', 'but', 'calm', 'come'],
    pairs: [
      {
        a: 'cart',
        b: 'cut',
        ipaA: '/kɑːt/',
        ipaB: '/kʌt/',
      },
      {
        a: 'heart',
        b: 'hut',
        ipaA: '/hɑːt/',
        ipaB: '/hʌt/',
      },
      {
        a: 'calm',
        b: 'come',
        ipaA: '/kɑːm/',
        ipaB: '/kʌm/',
      },
      {
        a: 'dark',
        b: 'duck',
        ipaA: '/dɑːk/',
        ipaB: '/dʌk/',
      },
    ],
  },
  {
    id: 'snd-v-schwa',
    symbol: '/ə/',
    name: 'the schwa (about, sofa)',
    level: 'B1',
    howTo:
      "Relax everything: jaw slightly open, tongue resting flat and central, lips neutral. Make a tiny, weak, unstressed 'uh' with no muscular effort. It is the shortest, laziest vowel in English and only appears in unstressed syllables.",
    examples: ['about', 'sofa', 'banana', 'problem', 'camera', 'support', 'under', 'the'],
    pairs: [
      {
        a: 'the (weak)',
        b: 'thee (strong)',
        ipaA: '/ðə/',
        ipaB: '/ðiː/',
        note: 'unstressed schwa vs full vowel',
      },
      {
        a: 'a (weak)',
        b: 'eh (strong)',
        ipaA: '/ə/',
        ipaB: '/eɪ/',
        note: 'the article reduced vs the letter name',
      },
      {
        a: 'to (weak)',
        b: 'too',
        ipaA: '/tə/',
        ipaB: '/tuː/',
        note: 'function word reduces to schwa',
      },
      {
        a: 'for (weak)',
        b: 'four',
        ipaA: '/fə/',
        ipaB: '/fɔː/',
        note: 'reduced preposition vs full word',
      },
    ],
  },
  {
    id: 'snd-v-ei-ai',
    symbol: '/eɪ/ vs /aɪ/',
    name: 'the ay and eye diphthongs (day/die)',
    level: 'A2',
    howTo:
      'For /eɪ/ start at /e/ (mouth mid-open) and glide upward toward /ɪ/, closing the jaw as you go. For /aɪ/ start with the mouth wide open at /a/ and glide up toward /ɪ/, a bigger movement. Both must be one smooth gliding sound, not two separate vowels.',
    examples: ['day', 'die', 'late', 'light', 'pain', 'pine', 'wait', 'white'],
    pairs: [
      {
        a: 'day',
        b: 'die',
        ipaA: '/deɪ/',
        ipaB: '/daɪ/',
      },
      {
        a: 'late',
        b: 'light',
        ipaA: '/leɪt/',
        ipaB: '/laɪt/',
      },
      {
        a: 'pain',
        b: 'pine',
        ipaA: '/peɪn/',
        ipaB: '/paɪn/',
      },
      {
        a: 'wait',
        b: 'white',
        ipaA: '/weɪt/',
        ipaB: '/waɪt/',
      },
    ],
  },
  {
    id: 'snd-v-ou-au',
    symbol: '/əʊ/ vs /aʊ/',
    name: 'the oh and ow diphthongs (go/cow)',
    level: 'B1',
    howTo:
      'For /əʊ/ (British) start at a central schwa /ə/ and glide toward /ʊ/, rounding the lips as you close - the American version /oʊ/ starts a little more rounded. For /aʊ/ start with the mouth wide open at /a/ and glide toward /ʊ/, rounding the lips at the end. Each is one smooth movement.',
    examples: ['go', 'cow', 'boat', 'about', 'know', 'now', 'load', 'loud'],
    pairs: [
      {
        a: 'go',
        b: 'cow',
        ipaA: '/ɡəʊ/',
        ipaB: '/kaʊ/',
        note: 'same glide ending, different start',
      },
      {
        a: 'low',
        b: 'loud',
        ipaA: '/ləʊ/',
        ipaB: '/laʊd/',
      },
      {
        a: 'phone',
        b: 'found',
        ipaA: '/fəʊn/',
        ipaB: '/faʊnd/',
      },
      {
        a: 'know',
        b: 'now',
        ipaA: '/nəʊ/',
        ipaB: '/naʊ/',
      },
    ],
  },
  {
    id: 'snd-v-oi',
    symbol: '/ɔɪ/',
    name: 'the oy diphthong (boy)',
    level: 'A2',
    howTo:
      "Start with the lips rounded and the tongue back at /ɔ/ (an open-mid 'aw'), then glide forward and up toward /ɪ/, unrounding and spreading the lips slightly as the tongue moves to the front. It is one smooth gliding syllable.",
    examples: ['boy', 'toy', 'coin', 'voice', 'enjoy', 'choice', 'oil', 'point'],
    pairs: [
      {
        a: 'boy',
        b: 'bay',
        ipaA: '/bɔɪ/',
        ipaB: '/beɪ/',
        note: 'oy glide vs ay glide',
      },
      {
        a: 'coin',
        b: 'cone',
        ipaA: '/kɔɪn/',
        ipaB: '/kəʊn/',
      },
      {
        a: 'oil',
        b: 'isle',
        ipaA: '/ɔɪl/',
        ipaB: '/aɪl/',
        note: 'oy vs eye',
      },
      {
        a: 'toy',
        b: 'tie',
        ipaA: '/tɔɪ/',
        ipaB: '/taɪ/',
      },
    ],
  },
  {
    id: 'snd-c1',
    symbol: '/θ/ vs /ð/',
    name: 'th sounds (think / this)',
    level: 'A2',
    howTo:
      'Put the tip of your tongue lightly between your teeth (or just touching the back of the upper front teeth) and push air out. For /θ/ (think) the vocal cords do NOT vibrate - it is just airflow. For /ð/ (this) keep the same tongue position but turn your voice on so the throat buzzes. Keep the tongue relaxed and let a little air leak around it.',
    examples: ['think', 'thank', 'three', 'month', 'this', 'that', 'mother', 'breathe'],
    pairs: [
      {
        a: 'think',
        b: 'sink',
        ipaA: '/θɪŋk/',
        ipaB: '/sɪŋk/',
        note: '/θ/ not /s/',
      },
      {
        a: 'thin',
        b: 'tin',
        ipaA: '/θɪn/',
        ipaB: '/tɪn/',
        note: '/θ/ not /t/',
      },
      {
        a: 'they',
        b: 'day',
        ipaA: '/ðeɪ/',
        ipaB: '/deɪ/',
        note: '/ð/ not /d/',
      },
      {
        a: 'breathe',
        b: 'breeze',
        ipaA: '/briːð/',
        ipaB: '/briːz/',
        note: '/ð/ not /z/',
      },
    ],
  },
  {
    id: 'snd-c2',
    symbol: '/b/ vs /v/',
    name: 'b vs v sounds (berry / very)',
    level: 'A1',
    howTo:
      'For /b/, press both lips fully together, build up air, then release - the lips touch. For /v/, do NOT use both lips: place your top teeth gently on your bottom lip and push air through while voicing, so you feel a buzzing vibration on your lip. The key difference is teeth-on-lip (/v/) versus lips-together (/b/).',
    examples: ['very', 'vote', 'van', 'love', 'river', 'save', 'voice', 'live'],
    pairs: [
      {
        a: 'berry',
        b: 'very',
        ipaA: '/ˈbɛri/',
        ipaB: '/ˈvɛri/',
        note: 'lips vs teeth-lip',
      },
      {
        a: 'boat',
        b: 'vote',
        ipaA: '/boʊt/',
        ipaB: '/voʊt/',
        note: 'initial /b/ vs /v/',
      },
      {
        a: 'ban',
        b: 'van',
        ipaA: '/bæn/',
        ipaB: '/væn/',
        note: '/b/ vs /v/',
      },
      {
        a: 'marble',
        b: 'marvel',
        ipaA: '/ˈmɑːrbəl/',
        ipaB: '/ˈmɑːrvəl/',
        note: 'medial contrast',
      },
    ],
  },
  {
    id: 'snd-c3',
    symbol: '/ʃ/ vs /tʃ/',
    name: 'sh vs ch sounds (ship / chip)',
    level: 'A2',
    howTo:
      "For /ʃ/ (sh), round your lips slightly and let a continuous stream of air flow over the middle of the tongue - it is a long, smooth hiss with no stop. For /tʃ/ (ch), start by briefly blocking the air with the tongue touching just behind the teeth ridge (like a 't'), then release it into the 'sh' - it is a quick burst, t + sh together.",
    examples: ['ship', 'shoe', 'wash', 'she', 'chip', 'cheese', 'watch', 'teacher'],
    pairs: [
      {
        a: 'ship',
        b: 'chip',
        ipaA: '/ʃɪp/',
        ipaB: '/tʃɪp/',
        note: 'continuous vs stop+release',
      },
      {
        a: 'share',
        b: 'chair',
        ipaA: '/ʃɛər/',
        ipaB: '/tʃɛər/',
        note: '/ʃ/ vs /tʃ/',
      },
      {
        a: 'wash',
        b: 'watch',
        ipaA: '/wɑːʃ/',
        ipaB: '/wɑːtʃ/',
        note: 'final contrast',
      },
      {
        a: 'sheep',
        b: 'cheap',
        ipaA: '/ʃiːp/',
        ipaB: '/tʃiːp/',
        note: 'initial contrast',
      },
    ],
  },
  {
    id: 'snd-c4',
    symbol: '/s/ vs /z/',
    name: 's vs z and final voicing (bus / buzz)',
    level: 'B1',
    howTo:
      "Both sounds use the same tongue position: tip near the ridge behind the upper teeth, air flowing in a thin stream. For /s/ the vocal cords are silent (a snake's hiss). For /z/ turn your voice on so you feel a buzz in your throat and on the tongue (a bee's buzz). Hold a finger to your throat: /z/ vibrates, /s/ does not.",
    examples: ['zoo', 'zebra', 'buzz', 'is', 'was', 'rose', 'easy', 'music'],
    pairs: [
      {
        a: 'bus',
        b: 'buzz',
        ipaA: '/bʌs/',
        ipaB: '/bʌz/',
        note: 'final voicing',
      },
      {
        a: 'price',
        b: 'prize',
        ipaA: '/praɪs/',
        ipaB: '/praɪz/',
        note: '/s/ vs /z/',
      },
      {
        a: 'sip',
        b: 'zip',
        ipaA: '/sɪp/',
        ipaB: '/zɪp/',
        note: 'initial contrast',
      },
      {
        a: 'racer',
        b: 'razor',
        ipaA: '/ˈreɪsər/',
        ipaB: '/ˈreɪzər/',
        note: 'medial contrast',
      },
    ],
  },
  {
    id: 'snd-c5',
    symbol: '/j/ vs /dʒ/',
    name: 'y vs j sounds (yet / jet)',
    level: 'A2',
    howTo:
      "For /j/ (the 'y' in yes), raise the middle of the tongue toward the roof of the mouth without touching it, voice on, and glide smoothly into the next vowel - air keeps flowing. For /dʒ/ (the 'j' in jet), press the tongue firmly against the ridge behind the teeth to stop the air, then release it into a 'zh' buzz - it is a hard, voiced burst.",
    examples: ['yes', 'year', 'yellow', 'young', 'jet', 'jump', 'judge', 'danger'],
    pairs: [
      {
        a: 'yet',
        b: 'jet',
        ipaA: '/jɛt/',
        ipaB: '/dʒɛt/',
        note: 'glide vs affricate',
      },
      {
        a: 'yam',
        b: 'jam',
        ipaA: '/jæm/',
        ipaB: '/dʒæm/',
        note: '/j/ vs /dʒ/',
      },
      {
        a: 'use (you)',
        b: 'juice',
        ipaA: '/juːz/',
        ipaB: '/dʒuːs/',
        note: 'initial contrast',
      },
      {
        a: 'year',
        b: 'jeer',
        ipaA: '/jɪər/',
        ipaB: '/dʒɪər/',
        note: 'initial contrast',
      },
    ],
  },
  {
    id: 'snd-c6',
    symbol: '-ed /t/ /d/ /ɪd/',
    name: 'past -ed endings (walked / played / wanted)',
    level: 'B1',
    howTo:
      "The regular past '-ed' has three pronunciations and you choose by the sound before it. If the verb ends in a voiceless sound (p, k, f, s, sh, ch), say /t/: 'walked' = walk-t. If it ends in a voiced sound or vowel, say /d/: 'played' = play-d. If it ends in /t/ or /d/, add a whole extra syllable /ɪd/: 'wanted' = want-id. Match the voicing of '-ed' to the sound just before it.",
    examples: ['walked', 'stopped', 'watched', 'played', 'lived', 'called', 'wanted', 'needed'],
    pairs: [
      {
        a: 'walked',
        b: 'wanted',
        ipaA: '/wɔːkt/',
        ipaB: '/ˈwɒntɪd/',
        note: '/t/ vs /ɪd/ (1 vs 2 syllables)',
      },
      {
        a: 'played',
        b: 'waited',
        ipaA: '/pleɪd/',
        ipaB: '/ˈweɪtɪd/',
        note: '/d/ vs /ɪd/',
      },
      {
        a: 'stopped',
        b: 'robbed',
        ipaA: '/stɒpt/',
        ipaB: '/rɒbd/',
        note: '/t/ vs /d/',
      },
      {
        a: 'missed',
        b: 'raised',
        ipaA: '/mɪst/',
        ipaB: '/reɪzd/',
        note: '/t/ vs /d/',
      },
    ],
  },
  {
    id: 'snd-c7',
    symbol: '-s /s/ /z/ /ɪz/',
    name: 'plural & 3rd-person -s (cats / dogs / buses)',
    level: 'B1',
    howTo:
      "The '-s' ending (plurals, possessives, he/she verbs) also has three sounds chosen by the sound before it. After a voiceless sound (p, t, k, f), say /s/: 'cats' = cat-s. After a voiced sound or vowel, say /z/: 'dogs' = dog-z. After a hissing/buzzing sound (s, z, sh, ch, j, x), add the syllable /ɪz/: 'buses' = bus-iz. Let your voice match what comes before it.",
    examples: ['cats', 'books', 'dogs', 'cars', 'goes', 'buses', 'watches', 'boxes'],
    pairs: [
      {
        a: 'cats',
        b: 'dogs',
        ipaA: '/kæts/',
        ipaB: '/dɒgz/',
        note: '/s/ vs /z/',
      },
      {
        a: 'books',
        b: 'boxes',
        ipaA: '/bʊks/',
        ipaB: '/ˈbɒksɪz/',
        note: '/s/ vs /ɪz/ (extra syllable)',
      },
      {
        a: 'maps',
        b: 'cabs',
        ipaA: '/mæps/',
        ipaB: '/kæbz/',
        note: '/s/ vs /z/',
      },
      {
        a: 'races',
        b: 'rates',
        ipaA: '/ˈreɪsɪz/',
        ipaB: '/reɪts/',
        note: '/ɪz/ vs /s/',
      },
    ],
  },
  {
    id: 'snd-c8',
    symbol: '/s/ + consonant',
    name: 'initial s-clusters (school, not eschool)',
    level: 'A2',
    howTo:
      "English words can begin with 's' plus another consonant (sp-, st-, sk-, sl-, sn-, sm-). Start the hiss of 's' immediately, with NO vowel before it - go straight from silence into 'ssschool'. Keep the 's' short and lead directly into the next consonant. Do not let your mouth add an 'eh' sound at the front.",
    examples: ['school', 'Spain', 'student', 'stop', 'small', 'snow', 'speak', 'street'],
    pairs: [
      {
        a: 'school',
        b: '(eschool)',
        ipaA: '/skuːl/',
        ipaB: '/ɛsˈkuːl/',
        note: 'no initial /ɛ/',
      },
      {
        a: 'Spain',
        b: '(espain)',
        ipaA: '/speɪn/',
        ipaB: '/ɛsˈpeɪn/',
        note: 'no initial /ɛ/',
      },
      {
        a: 'student',
        b: '(estudent)',
        ipaA: '/ˈstjuːdənt/',
        ipaB: '/ɛsˈtjuːdənt/',
        note: 'no initial /ɛ/',
      },
      {
        a: 'speak',
        b: '(espeak)',
        ipaA: '/spiːk/',
        ipaB: '/ɛsˈpiːk/',
        note: 'no initial /ɛ/',
      },
    ],
  },
  {
    id: 'snd-c9',
    symbol: '/h/',
    name: 'the h sound (house, hello)',
    level: 'A1',
    howTo:
      'English /h/ is a gentle puff of air from the throat, like fogging up a mirror or a quiet sigh, made BEFORE the vowel. The mouth is already shaped for the following vowel; you just breathe out audibly first. There is no friction at the back of the mouth - it is soft breath, not a scrape.',
    examples: ['house', 'hello', 'happy', 'hand', 'behind', 'hot', 'who', 'perhaps'],
    pairs: [
      {
        a: 'house',
        b: '(ouse)',
        ipaA: '/haʊs/',
        ipaB: '/aʊs/',
        note: "don't drop /h/",
      },
      {
        a: 'hate',
        b: 'eight',
        ipaA: '/heɪt/',
        ipaB: '/eɪt/',
        note: '/h/ vs no /h/',
      },
      {
        a: 'heart',
        b: 'art',
        ipaA: '/hɑːrt/',
        ipaB: '/ɑːrt/',
        note: '/h/ vs no /h/',
      },
      {
        a: 'hill',
        b: 'ill',
        ipaA: '/hɪl/',
        ipaB: '/ɪl/',
        note: '/h/ vs no /h/',
      },
    ],
  },
  {
    id: 'snd-c10',
    symbol: 'ˈstress',
    name: 'word stress patterns (PHOtograph / phoTOgrapher)',
    level: 'B2',
    howTo:
      'Every English word of two or more syllables has one strong (stressed) syllable: say it louder, longer, higher in pitch, and with a clear full vowel. The other syllables are weak and shrink toward the neutral schwa /ə/. Find the stressed syllable, stretch it, and let the rest become short and quiet. Stress can shift when you add endings, changing the whole rhythm.',
    examples: [
      'photograph',
      'photographer',
      'present',
      'record',
      'develop',
      'important',
      'comfortable',
      'necessary',
    ],
    pairs: [
      {
        a: 'PREsent (noun)',
        b: 'preSENT (verb)',
        ipaA: '/ˈprɛzənt/',
        ipaB: '/prɪˈzɛnt/',
        note: 'stress changes meaning',
      },
      {
        a: 'REcord (noun)',
        b: 'reCORD (verb)',
        ipaA: '/ˈrɛkɔːrd/',
        ipaB: '/rɪˈkɔːrd/',
        note: 'noun vs verb stress',
      },
      {
        a: 'PHOtograph',
        b: 'phoTOgrapher',
        ipaA: '/ˈfoʊtəˌɡræf/',
        ipaB: '/fəˈtɒɡrəfər/',
        note: 'stress shifts with suffix',
      },
      {
        a: 'OBject (noun)',
        b: 'obJECT (verb)',
        ipaA: '/ˈɒbdʒɪkt/',
        ipaB: '/əbˈdʒɛkt/',
        note: 'noun vs verb stress',
      },
    ],
  },
];
