import type { PhrasalVerb } from '../types';

// High-frequency phrasal verbs. Generated content.
export const PHRASAL: PhrasalVerb[] = [
  {
    id: 'pv-get-up',
    verb: 'get up',
    meaning: 'to rise from bed or stand up',
    es: 'levantarse',
    example: 'I get up at seven every morning.',
    level: 'A1',
    separable: false,
  },
  {
    id: 'pv-get-on-off',
    verb: 'get on/off',
    meaning: 'to board or leave a bus, train, or plane',
    es: 'subir/bajar (de un transporte)',
    example: 'We get on the bus here and get off at the station.',
    level: 'A1',
    separable: false,
  },
  {
    id: 'pv-get-along-with',
    verb: 'get along with',
    meaning: 'to have a friendly relationship with someone',
    es: 'llevarse bien con',
    example: 'She gets along with all of her coworkers.',
    level: 'B1',
    separable: false,
  },
  {
    id: 'pv-put-on',
    verb: 'put on',
    meaning: 'to dress oneself in clothing',
    es: 'ponerse (ropa)',
    example: "Put on your coat; it's cold outside. / Put your coat on before you leave.",
    level: 'A1',
    separable: true,
  },
  {
    id: 'pv-take-off',
    verb: 'take off',
    meaning: 'to remove clothing, or for a plane to leave the ground',
    es: 'quitarse / despegar',
    example: 'He took off his shoes at the door. / He took his shoes off at the door.',
    level: 'A2',
    separable: true,
  },
  {
    id: 'pv-turn-on-off',
    verb: 'turn on/off',
    meaning: 'to start or stop a device or light',
    es: 'encender/apagar',
    example: 'Please turn on the lights. / Turn the lights off when you leave.',
    level: 'A1',
    separable: true,
  },
  {
    id: 'pv-turn-up-down',
    verb: 'turn up/down',
    meaning: 'to increase or decrease volume or intensity',
    es: 'subir/bajar (volumen, intensidad)',
    example: 'Can you turn up the music? / Turn the music down, please.',
    level: 'A2',
    separable: true,
  },
  {
    id: 'pv-look-for',
    verb: 'look for',
    meaning: 'to try to find someone or something',
    es: 'buscar',
    example: "I'm looking for my keys.",
    level: 'A1',
    separable: false,
  },
  {
    id: 'pv-look-after',
    verb: 'look after',
    meaning: 'to take care of someone or something',
    es: 'cuidar de',
    example: 'She looks after her younger brother after school.',
    level: 'A2',
    separable: false,
  },
  {
    id: 'pv-look-up',
    verb: 'look up',
    meaning: 'to search for information in a reference source',
    es: 'buscar (información)',
    example: "Look up the word in the dictionary. / Look it up if you don't know it.",
    level: 'A2',
    separable: true,
  },
  {
    id: 'pv-look-forward-to',
    verb: 'look forward to',
    meaning: 'to feel excited about something in the future',
    es: 'esperar con ilusión',
    example: 'I look forward to seeing you next week.',
    level: 'B1',
    separable: false,
  },
  {
    id: 'pv-give-up',
    verb: 'give up',
    meaning: 'to stop trying or quit a habit',
    es: 'rendirse / dejar (un hábito)',
    example: "Don't give up on your dreams. / He gave smoking up last year.",
    level: 'A2',
    separable: true,
  },
  {
    id: 'pv-give-back',
    verb: 'give back',
    meaning: 'to return something to its owner',
    es: 'devolver',
    example: "Please give back my pen. / Give it back when you're done.",
    level: 'A2',
    separable: true,
  },
  {
    id: 'pv-pick-up',
    verb: 'pick up',
    meaning: 'to lift something, or collect someone',
    es: 'recoger / levantar',
    example: "I'll pick up the kids from school. / Pick them up at three o'clock.",
    level: 'A2',
    separable: true,
  },
  {
    id: 'pv-find-out',
    verb: 'find out',
    meaning: 'to discover information',
    es: 'averiguar',
    example: 'I need to find out what time the movie starts. / Find it out before noon.',
    level: 'A2',
    separable: true,
  },
  {
    id: 'pv-come-back',
    verb: 'come back',
    meaning: 'to return to a place',
    es: 'volver / regresar',
    example: 'Come back home before dark.',
    level: 'A1',
    separable: false,
  },
  {
    id: 'pv-come-up-with',
    verb: 'come up with',
    meaning: 'to think of an idea or solution',
    es: 'idear / ocurrírsele',
    example: 'She came up with a great plan.',
    level: 'B1',
    separable: false,
  },
  {
    id: 'pv-go-on',
    verb: 'go on',
    meaning: 'to continue, or to happen',
    es: 'continuar / suceder',
    example: 'Please go on with your story.',
    level: 'A2',
    separable: false,
  },
  {
    id: 'pv-go-out',
    verb: 'go out',
    meaning: 'to leave home for a social activity',
    es: 'salir',
    example: 'We go out for dinner every Friday.',
    level: 'A1',
    separable: false,
  },
  {
    id: 'pv-carry-on',
    verb: 'carry on',
    meaning: 'to continue doing something',
    es: 'seguir / continuar',
    example: 'Carry on working while I make a call.',
    level: 'B1',
    separable: false,
  },
  {
    id: 'pv-carry-out',
    verb: 'carry out',
    meaning: 'to perform or complete a task',
    es: 'llevar a cabo / realizar',
    example: 'The team carried out the experiment. / They carried it out carefully.',
    level: 'B1',
    separable: true,
  },
  {
    id: 'pv-set-up',
    verb: 'set up',
    meaning: 'to establish or arrange something',
    es: 'montar / establecer',
    example: 'They set up a new company. / They set it up last year.',
    level: 'B1',
    separable: true,
  },
  {
    id: 'pv-take-over',
    verb: 'take over',
    meaning: 'to take control of something',
    es: 'hacerse cargo / tomar el control',
    example: 'A new manager took over the department. / She took it over in May.',
    level: 'B1',
    separable: true,
  },
  {
    id: 'pv-bring-up',
    verb: 'bring up',
    meaning: 'to raise a child, or to mention a topic',
    es: 'criar / sacar un tema',
    example: "He was brought up by his grandparents. / Don't bring that up at dinner.",
    level: 'B1',
    separable: true,
  },
  {
    id: 'pv-break-down',
    verb: 'break down',
    meaning: 'to stop working, or to lose emotional control',
    es: 'averiarse / derrumbarse',
    example: 'My car broke down on the highway.',
    level: 'B1',
    separable: false,
  },
  {
    id: 'pv-break-up',
    verb: 'break up',
    meaning: 'to end a romantic relationship',
    es: 'romper / terminar (una relación)',
    example: 'They broke up after five years together.',
    level: 'B1',
    separable: false,
  },
  {
    id: 'pv-run-out-of',
    verb: 'run out of',
    meaning: 'to use up all of a supply',
    es: 'quedarse sin',
    example: 'We ran out of milk this morning.',
    level: 'B1',
    separable: false,
  },
  {
    id: 'pv-work-out',
    verb: 'work out',
    meaning: 'to solve, to exercise, or to turn out well',
    es: 'resolver / hacer ejercicio',
    example:
      "I work out at the gym every day. / Let's work out the answer. / Work it out together.",
    level: 'B1',
    separable: true,
  },
  {
    id: 'pv-figure-out',
    verb: 'figure out',
    meaning: 'to understand or solve something',
    es: 'descifrar / resolver',
    example: "I can't figure out this problem. / I'll figure it out eventually.",
    level: 'B1',
    separable: true,
  },
  {
    id: 'pv-fill-in',
    verb: 'fill in',
    meaning: 'to complete a form with information',
    es: 'rellenar / completar',
    example: 'Please fill in the application form. / Fill it in with a black pen.',
    level: 'B1',
    separable: true,
  },
  {
    id: 'pv-put-up-with',
    verb: 'put up with',
    meaning: 'to tolerate something unpleasant',
    es: 'aguantar / soportar',
    example: "I can't put up with the noise any longer.",
    level: 'B2',
    separable: false,
  },
  {
    id: 'pv-make-up',
    verb: 'make up',
    meaning: 'to invent a story, or to reconcile',
    es: 'inventar / reconciliarse',
    example: 'He made up an excuse. / She made it up on the spot.',
    level: 'B1',
    separable: true,
  },
  {
    id: 'pv-deal-with',
    verb: 'deal with',
    meaning: 'to handle or manage a problem or situation',
    es: 'lidiar con / tratar',
    example: 'We need to deal with this issue today.',
    level: 'B1',
    separable: false,
  },
  {
    id: 'pv-call-off',
    verb: 'call off',
    meaning: 'to cancel an event or plan',
    es: 'cancelar / suspender',
    example: 'They called off the wedding. / They called it off at the last minute.',
    level: 'B1',
    separable: true,
  },
  {
    id: 'pv-hang-up',
    verb: 'hang up',
    meaning: 'to end a phone call',
    es: 'colgar (el teléfono)',
    example: "She hung up the phone angrily. / Don't hang up on me!",
    level: 'B1',
    separable: true,
  },
  {
    id: 'pv-show-up',
    verb: 'show up',
    meaning: 'to arrive or appear',
    es: 'aparecer / presentarse',
    example: 'He showed up late to the meeting.',
    level: 'B1',
    separable: false,
  },
  {
    id: 'pv-sort-out',
    verb: 'sort out',
    meaning: 'to organize or resolve a problem',
    es: 'arreglar / solucionar',
    example: "Let's sort out this mess. / I'll sort it out tomorrow.",
    level: 'B2',
    separable: true,
  },
  {
    id: 'pv-cut-down-on',
    verb: 'cut down on',
    meaning: 'to reduce the amount of something',
    es: 'reducir / disminuir',
    example: 'You should cut down on sugar.',
    level: 'B2',
    separable: false,
  },
  {
    id: 'pv-get-over',
    verb: 'get over',
    meaning: 'to recover from an illness or difficult experience',
    es: 'superar / recuperarse de',
    example: 'It took her months to get over the breakup.',
    level: 'B2',
    separable: false,
  },
  {
    id: 'pv-end-up',
    verb: 'end up',
    meaning: 'to eventually be in a situation or place',
    es: 'acabar / terminar (en una situación)',
    example: 'We ended up staying home all weekend.',
    level: 'B1',
    separable: false,
  },
];
