import type { SpanishPitfall } from '../types';

// The Spanish-speaker pitfalls strand: the predictable L1-interference errors —
// false friends, grammar traps, and pronunciation interference — each shown as
// wrong → right with the reason. Seeded here; expanded by the content pipeline.

export const PITFALLS: SpanishPitfall[] = [
  {
    id: 'pf-actually',
    category: 'false-friend',
    title: 'actually ≠ actualmente',
    wrong: 'Actually, I live in Madrid. (meaning: currently)',
    right: 'Currently / Right now, I live in Madrid.',
    explain: "**actually** means 'in reality / in fact', not 'currently'.",
    esNote: "'actualmente' = currently. 'actually' = en realidad, de hecho.",
    level: 'A2',
  },
  {
    id: 'pf-library',
    category: 'false-friend',
    title: 'library ≠ librería',
    wrong: 'I bought this book at the library.',
    right: 'I bought this book at the bookshop / bookstore.',
    explain: '**library** is where you borrow books for free (biblioteca).',
    esNote: "'librería' (where you buy books) = bookshop/bookstore.",
    level: 'A2',
  },
  {
    id: 'pf-embarrassed',
    category: 'false-friend',
    title: 'embarrassed ≠ embarazada',
    wrong: "She's embarrassed — the baby is due in May.",
    right: "She's pregnant — the baby is due in May.",
    explain: '**embarrassed** means feeling ashamed/awkward (avergonzado).',
    esNote: "'embarazada' = pregnant. This false friend can be very awkward!",
    level: 'B1',
  },
  {
    id: 'pf-do-support-q',
    category: 'grammar',
    title: 'Questions need do/does',
    wrong: 'You like coffee?',
    right: 'Do you like coffee?',
    explain: 'Present simple yes/no questions need the auxiliary **do/does**.',
    esNote: "El español no usa auxiliar; el inglés sí: 'Do you...?'.",
    level: 'A1',
  },
  {
    id: 'pf-third-s',
    category: 'grammar',
    title: 'Third-person -s',
    wrong: 'He live in Barcelona.',
    right: 'He lives in Barcelona.',
    explain: 'Add **-s** to the verb with he/she/it in the present simple.',
    esNote: 'Es el error gramatical más frecuente entre hispanohablantes.',
    level: 'A1',
  },
  {
    id: 'pf-adj-order',
    category: 'word-order',
    title: 'Adjective before noun',
    wrong: 'a car red',
    right: 'a red car',
    explain: 'In English the adjective comes **before** the noun.',
    esNote: "En español el adjetivo suele ir después ('un coche rojo').",
    level: 'A1',
  },
  {
    id: 'pf-depend-on',
    category: 'preposition',
    title: 'depend on (not "of")',
    wrong: 'It depends of the weather.',
    right: 'It depends on the weather.',
    explain: 'The correct preposition is **on**: depend on.',
    esNote: "'depender de' → depend ON. No traduzcas 'de' como 'of' aquí.",
    level: 'A2',
  },
  {
    id: 'pf-married-to',
    category: 'preposition',
    title: 'married to (not "with")',
    wrong: "She's married with a doctor.",
    right: "She's married to a doctor.",
    explain: 'You are married **to** someone.',
    esNote: "'casado con' → married TO. ('married with children' = tener hijos.)",
    level: 'B1',
  },
  {
    id: 'pf-s-cluster',
    category: 'pronunciation',
    title: 'No /e/ before s-clusters',
    wrong: 'eSpain, eSchool, eStreet',
    right: 'Spain, school, street',
    explain: "Don't add a vowel before initial **s + consonant**. Start with the /s/.",
    esNote: 'El español añade una /e/ (España); el inglés empieza directo con /s/.',
    level: 'A1',
  },
  {
    id: 'pf-double-neg',
    category: 'grammar',
    title: 'No double negatives',
    wrong: "I don't see nobody.",
    right: "I don't see anybody.",
    explain: 'Use **anybody/anything** after a negative, not nobody/nothing.',
    esNote: "El español permite doble negación ('no veo a nadie'); el inglés no.",
    level: 'A2',
  },
];
