import type { Reading } from '../types';

// Graded comprehensible-input texts. Generated content.
export const READINGS: Reading[] = [
  {
    id: 'rd-my-morning',
    level: 'A1',
    title: 'My Morning',
    blurb: "A simple description of a person's morning routine.",
    paragraphs: [
      "I get up at seven o'clock. I open the window and look at the sky. The morning is quiet.",
      'I drink a glass of water. Then I make coffee. I like my coffee with a little milk.',
      'I eat bread and an egg for breakfast. My cat sits next to me. She wants food too.',
      "At eight o'clock I put on my shoes. I take my bag and go to work. I walk because the office is near.",
    ],
    questions: [
      {
        kind: 'mcq',
        id: 'q1',
        prompt: 'What time does the person get up?',
        options: ["At six o'clock", "At seven o'clock", "At eight o'clock", "At nine o'clock"],
        answer: 1,
        explain: 'The text says "I get up at seven o\'clock."',
      },
      {
        kind: 'mcq',
        id: 'q2',
        prompt: 'How does the person go to work?',
        options: ['By car', 'By bus', 'On foot (walking)', 'By train'],
        answer: 2,
        explain: 'The text says "I walk because the office is near."',
      },
      {
        kind: 'mcq',
        id: 'q3',
        prompt: 'What animal is with the person at breakfast?',
        options: ['A dog', 'A bird', 'A cat', 'A fish'],
        answer: 2,
        explain: 'The text says "My cat sits next to me."',
      },
    ],
  },
  {
    id: 'rd-my-family',
    level: 'A1',
    title: 'My Family',
    blurb: 'A short, simple text where someone introduces their family.',
    paragraphs: [
      'My name is Ana. I live in a small house with my family. We are five people.',
      'My father is a doctor. My mother is a teacher. They work in the city.',
      'I have one brother and one sister. My brother is ten years old. My sister is a baby.',
      'We have a dog. His name is Max. He is big and brown. I love my family very much.',
    ],
    questions: [
      {
        kind: 'mcq',
        id: 'q1',
        prompt: "How many people are in Ana's family?",
        options: ['Three', 'Four', 'Five', 'Six'],
        answer: 2,
        explain: 'The text says "We are five people."',
      },
      {
        kind: 'mcq',
        id: 'q2',
        prompt: "What is Ana's mother's job?",
        options: ['A doctor', 'A teacher', 'A nurse', 'A cook'],
        answer: 1,
        explain: 'The text says "My mother is a teacher."',
      },
      {
        kind: 'mcq',
        id: 'q3',
        prompt: "What is the dog's name?",
        options: ['Ana', 'Max', 'Sam', 'Leo'],
        answer: 1,
        explain: 'The text says "His name is Max."',
      },
    ],
  },
  {
    id: 'rd-a-day-at-the-beach',
    level: 'A2',
    title: 'A Day at the Beach',
    blurb: 'A short story about a family trip to the beach on a sunny day.',
    paragraphs: [
      'Last Saturday, my family went to the beach. It was a hot and sunny day, so we left home early in the morning.',
      'When we arrived, we put our towels on the sand. My little sister wanted to swim, but the water was cold at first. My father played football with me near the sea.',
      'At lunchtime, we ate sandwiches and fruit. A big seagull tried to take my sandwich! Everybody laughed.',
      'In the afternoon, we built a sandcastle and looked for shells. We went home tired but happy. It was a wonderful day.',
    ],
    questions: [
      {
        kind: 'mcq',
        id: 'q1',
        prompt: 'When did the family go to the beach?',
        options: ['Last Sunday', 'Last Saturday', 'Last Friday', 'Last Monday'],
        answer: 1,
        explain: 'The text says "Last Saturday, my family went to the beach."',
      },
      {
        kind: 'mcq',
        id: 'q2',
        prompt: 'Why did everybody laugh?',
        options: [
          'The water was cold',
          'A seagull tried to take a sandwich',
          'They built a sandcastle',
          'They went home early',
        ],
        answer: 1,
        explain: 'The text says "A big seagull tried to take my sandwich! Everybody laughed."',
      },
      {
        kind: 'mcq',
        id: 'q3',
        prompt: 'How did they feel at the end of the day?',
        options: ['Tired but happy', 'Sad and cold', 'Bored', 'Angry'],
        answer: 0,
        explain: 'The text says "We went home tired but happy."',
      },
    ],
  },
  {
    id: 'rd-email-to-a-friend',
    level: 'A2',
    title: 'An Email to a Friend',
    blurb: 'An informal email inviting a friend to visit a new city.',
    paragraphs: [
      'Hi Carlos,\n\nHow are you? I hope you are well. I am writing from my new city. I moved here two weeks ago for my new job.',
      'The city is bigger than my old town. There are many shops, parks, and nice cafés. My apartment is small but comfortable, and it is close to the river.',
      'My job is interesting, but I am still learning a lot. My colleagues are friendly and they help me every day.',
      "Why don't you visit me next month? There is a free room for you. We can walk in the parks and try the local food. Please write back soon!\n\nYour friend,\nMiguel",
    ],
    questions: [
      {
        kind: 'mcq',
        id: 'q1',
        prompt: 'Why did Miguel move to the new city?',
        options: ['For a holiday', 'For his new job', 'To study', 'To see his family'],
        answer: 1,
        explain: 'The text says "I moved here two weeks ago for my new job."',
      },
      {
        kind: 'mcq',
        id: 'q2',
        prompt: 'What does Miguel say about his apartment?',
        options: [
          'It is big but far away',
          'It is small but comfortable',
          'It is old and cold',
          'It has no rooms',
        ],
        answer: 1,
        explain:
          'The text says "My apartment is small but comfortable, and it is close to the river."',
      },
      {
        kind: 'mcq',
        id: 'q3',
        prompt: 'What does Miguel ask Carlos to do?',
        options: ['Find him a job', 'Visit him next month', 'Send him money', 'Move to the city'],
        answer: 1,
        explain: 'The text says "Why don\'t you visit me next month?"',
      },
    ],
  },
  {
    id: 'rd-the-history-of-chocolate',
    level: 'B1',
    title: 'The History of Chocolate',
    blurb: 'An informative article about where chocolate comes from and how it changed over time.',
    paragraphs: [
      'Chocolate is one of the most popular foods in the world, but few people know about its long history. It comes from the seeds of the cacao tree, which grows in warm, rainy regions near the equator.',
      'More than three thousand years ago, ancient peoples in Central America were already using cacao. The Maya and the Aztecs made a bitter drink from the seeds. They mixed it with water and spices, and they believed it gave them energy and strength.',
      'When Spanish explorers arrived in the Americas, they took cacao back to Europe. At first, the drink was only for rich people because it was expensive. Later, cooks added sugar and milk, and chocolate became sweeter and more popular.',
      'In the nineteenth century, new machines made it possible to produce solid chocolate bars. Today, factories around the world turn cacao into thousands of different products. However, the cacao tree still grows mostly in the same warm countries as before.',
    ],
    questions: [
      {
        kind: 'mcq',
        id: 'q1',
        prompt: 'Where does chocolate originally come from?',
        options: [
          'From the leaves of a bush',
          'From the seeds of the cacao tree',
          'From a type of grass',
          'From a flower',
        ],
        answer: 1,
        explain: 'The text says it "comes from the seeds of the cacao tree."',
      },
      {
        kind: 'mcq',
        id: 'q2',
        prompt: 'How did the Maya and Aztecs use cacao?',
        options: [
          'They made a sweet cake',
          'They made a bitter drink',
          'They ate the leaves',
          'They used it as money only',
        ],
        answer: 1,
        explain: 'The text says "The Maya and the Aztecs made a bitter drink from the seeds."',
      },
      {
        kind: 'mcq',
        id: 'q3',
        prompt: 'Why was chocolate only for rich people in Europe at first?',
        options: ['It was illegal', 'It was expensive', 'It was dangerous', 'It was hard to drink'],
        answer: 1,
        explain: 'The text says "the drink was only for rich people because it was expensive."',
      },
    ],
  },
  {
    id: 'rd-learning-a-language',
    level: 'B1',
    title: 'Why Learning a Language Changes You',
    blurb: 'A reflective article about the benefits of learning a new language.',
    paragraphs: [
      'Learning a new language is not only about words and grammar. It is also a way of opening a door to a different culture and a different way of thinking.',
      'Many people give up too early because they feel embarrassed when they make mistakes. However, mistakes are a normal and necessary part of the process. Every time you say something wrong and then correct it, your brain learns a little more.',
      'Research suggests that speaking more than one language can improve your memory and help you focus. Some studies even show that bilingual people are better at solving certain kinds of problems.',
      'Perhaps the best reward, though, is human connection. When you speak to someone in their own language, you show respect and you build trust. A simple conversation can become the start of a real friendship.',
    ],
    questions: [
      {
        kind: 'mcq',
        id: 'q1',
        prompt: 'According to the text, why do many people give up too early?',
        options: [
          'They have no time',
          'They feel embarrassed when they make mistakes',
          'The books are too expensive',
          'They already speak many languages',
        ],
        answer: 1,
        explain:
          'The text says people "give up too early because they feel embarrassed when they make mistakes."',
      },
      {
        kind: 'mcq',
        id: 'q2',
        prompt: 'What does research suggest about speaking more than one language?',
        options: [
          'It makes you tired',
          'It can improve memory and focus',
          'It is bad for the brain',
          'It only helps children',
        ],
        answer: 1,
        explain: 'The text says it "can improve your memory and help you focus."',
      },
      {
        kind: 'mcq',
        id: 'q3',
        prompt: 'What does the writer call the best reward of learning a language?',
        options: ['Money', 'Human connection', 'A better memory', 'Faster reading'],
        answer: 1,
        explain: 'The text says "the best reward, though, is human connection."',
      },
    ],
  },
  {
    id: 'rd-remote-work-debate',
    level: 'B2',
    title: 'The Remote Work Debate',
    blurb: 'A balanced article weighing the advantages and drawbacks of working from home.',
    paragraphs: [
      'Over the past decade, and especially since the global pandemic, working from home has shifted from a rare privilege to an everyday reality for millions of employees. Yet despite its popularity, remote work remains a topic of heated debate among workers and managers alike.',
      'Supporters argue that the benefits are clear. Without a daily commute, people save both time and money, and many report a better balance between their professional and personal lives. Companies, in turn, can recruit talented staff regardless of where they live, and some have even reduced costs by closing expensive offices.',
      'Critics, however, point to subtler problems. Collaboration can suffer when colleagues rarely meet face to face, and spontaneous conversations, which often spark new ideas, become much harder to replicate online. Younger employees, in particular, may miss out on the informal mentoring that happens naturally in an office.',
      'Perhaps the most likely outcome is a compromise. So-called hybrid models, in which staff split their week between home and the office, attempt to capture the advantages of both worlds. Whether they truly succeed will depend less on technology and more on how thoughtfully organisations manage the change.',
    ],
    questions: [
      {
        kind: 'mcq',
        id: 'q1',
        prompt: 'According to supporters, what is one benefit of remote work for companies?',
        options: [
          'Employees work longer hours',
          'They can recruit talented staff regardless of location',
          'Offices become more crowded',
          'Workers never need training',
        ],
        answer: 1,
        explain:
          'The text says companies "can recruit talented staff regardless of where they live."',
      },
      {
        kind: 'mcq',
        id: 'q2',
        prompt: 'What concern do critics raise about remote work?',
        options: [
          'It costs too much money',
          'Collaboration can suffer without face-to-face contact',
          'Commuting becomes longer',
          'Offices become too expensive',
        ],
        answer: 1,
        explain:
          'The text says "Collaboration can suffer when colleagues rarely meet face to face."',
      },
      {
        kind: 'mcq',
        id: 'q3',
        prompt: 'What does the article suggest is the most likely outcome?',
        options: [
          'A full return to the office',
          'A complete end to office work',
          'A hybrid compromise',
          'A ban on remote work',
        ],
        answer: 2,
        explain:
          'The text describes "hybrid models" as a compromise and the "most likely outcome."',
      },
    ],
  },
  {
    id: 'rd-attention-economy',
    level: 'C1',
    title: 'The Attention Economy',
    blurb: 'An analytical essay on how digital platforms compete for our limited attention.',
    paragraphs: [
      'In an age of seemingly infinite information, the truly scarce resource is no longer content but attention. Every notification, headline, and autoplaying video is engineered to capture a sliver of our focus, and the companies that succeed in doing so are rewarded handsomely. This is the logic of what economists and critics have come to call the attention economy.',
      'The mechanics are deceptively simple. Platforms offer their services free of charge, then monetise the engagement they generate by selling advertisers access to our eyes and minds. Because attention is finite, the competition is necessarily zero-sum: every minute spent on one application is a minute unavailable to another. To win, designers exploit well-documented psychological vulnerabilities, from our craving for social approval to our reluctance to leave a task unfinished.',
      'The consequences extend well beyond individual productivity. When outrage and novelty reliably generate engagement, platforms have a structural incentive to amplify precisely the content most likely to inflame rather than inform. Nuance, which rarely goes viral, is quietly disadvantaged, and public discourse grows coarser as a result.',
      'None of this implies that users are merely passive victims. Awareness of these dynamics, combined with deliberate habits and, where necessary, sensible regulation, can restore a measure of agency. The first step, however, is to recognise that our attention is not an inexhaustible commodity to be spent thoughtlessly, but a finite and valuable resource worth defending.',
    ],
    questions: [
      {
        kind: 'mcq',
        id: 'q1',
        prompt: 'According to the essay, what is the truly scarce resource today?',
        options: [
          'Content and information',
          'Attention',
          'Money for advertising',
          'Internet access',
        ],
        answer: 1,
        explain: 'The text states "the truly scarce resource is no longer content but attention."',
      },
      {
        kind: 'mcq',
        id: 'q2',
        prompt: "Why does the author describe the competition for attention as 'zero-sum'?",
        options: [
          'Because attention costs nothing',
          'Because time spent on one app is unavailable to another',
          'Because all platforms are free',
          'Because advertisers never profit',
        ],
        answer: 1,
        explain:
          'The text explains "every minute spent on one application is a minute unavailable to another."',
      },
      {
        kind: 'mcq',
        id: 'q3',
        prompt: 'What does the author suggest can help users regain control?',
        options: [
          'Ignoring the problem entirely',
          'Awareness, deliberate habits, and sensible regulation',
          'Spending more time online',
          'Trusting platforms completely',
        ],
        answer: 1,
        explain:
          'The text says "Awareness of these dynamics, combined with deliberate habits and... sensible regulation, can restore a measure of agency."',
      },
    ],
  },
];
