/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as PronunciationRouteImport } from './routes/pronunciation'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as PhrasalRouteImport } from './routes/phrasal'
import { Route as IdiomsRouteImport } from './routes/idioms'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoadmapIndexRouteImport } from './routes/roadmap/index'
import { Route as RoadmapLevelRouteRouteImport } from './routes/roadmap/$level/route'
import { Route as RoadmapLevelIndexRouteImport } from './routes/roadmap/$level/index'
import { Route as RoadmapLevelLessonIdRouteImport } from './routes/roadmap/$level/$lessonId'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationRoute = PronunciationRouteImport.update({
  id: '/pronunciation',
  path: '/pronunciation',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const PhrasalRoute = PhrasalRouteImport.update({
  id: '/phrasal',
  path: '/phrasal',
  getParentRoute: () => rootRouteImport,
} as any)
const IdiomsRoute = IdiomsRouteImport.update({
  id: '/idioms',
  path: '/idioms',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapIndexRoute = RoadmapIndexRouteImport.update({
  id: '/roadmap/',
  path: '/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapLevelRouteRoute = RoadmapLevelRouteRouteImport.update({
  id: '/roadmap/$level',
  path: '/roadmap/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapLevelIndexRoute = RoadmapLevelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoadmapLevelRouteRoute,
} as any)
const RoadmapLevelLessonIdRoute = RoadmapLevelLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => RoadmapLevelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drill': typeof DrillRoute
  '/grammar': typeof GrammarRoute
  '/idioms': typeof IdiomsRoute
  '/phrasal': typeof PhrasalRoute
  '/placement': typeof PlacementRoute
  '/pronunciation': typeof PronunciationRoute
  '/reading': typeof ReadingRoute
  '/review': typeof ReviewRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing': typeof WritingRoute
  '/roadmap/$level': typeof RoadmapLevelRouteRouteWithChildren
  '/roadmap/': typeof RoadmapIndexRoute
  '/roadmap/$level/$lessonId': typeof RoadmapLevelLessonIdRoute
  '/roadmap/$level/': typeof RoadmapLevelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drill': typeof DrillRoute
  '/grammar': typeof GrammarRoute
  '/idioms': typeof IdiomsRoute
  '/phrasal': typeof PhrasalRoute
  '/placement': typeof PlacementRoute
  '/pronunciation': typeof PronunciationRoute
  '/reading': typeof ReadingRoute
  '/review': typeof ReviewRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing': typeof WritingRoute
  '/roadmap': typeof RoadmapIndexRoute
  '/roadmap/$level/$lessonId': typeof RoadmapLevelLessonIdRoute
  '/roadmap/$level': typeof RoadmapLevelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drill': typeof DrillRoute
  '/grammar': typeof GrammarRoute
  '/idioms': typeof IdiomsRoute
  '/phrasal': typeof PhrasalRoute
  '/placement': typeof PlacementRoute
  '/pronunciation': typeof PronunciationRoute
  '/reading': typeof ReadingRoute
  '/review': typeof ReviewRoute
  '/vocabulary': typeof VocabularyRoute
  '/writing': typeof WritingRoute
  '/roadmap/$level': typeof RoadmapLevelRouteRouteWithChildren
  '/roadmap/': typeof RoadmapIndexRoute
  '/roadmap/$level/$lessonId': typeof RoadmapLevelLessonIdRoute
  '/roadmap/$level/': typeof RoadmapLevelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drill'
    | '/grammar'
    | '/idioms'
    | '/phrasal'
    | '/placement'
    | '/pronunciation'
    | '/reading'
    | '/review'
    | '/vocabulary'
    | '/writing'
    | '/roadmap/$level'
    | '/roadmap/'
    | '/roadmap/$level/$lessonId'
    | '/roadmap/$level/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drill'
    | '/grammar'
    | '/idioms'
    | '/phrasal'
    | '/placement'
    | '/pronunciation'
    | '/reading'
    | '/review'
    | '/vocabulary'
    | '/writing'
    | '/roadmap'
    | '/roadmap/$level/$lessonId'
    | '/roadmap/$level'
  id:
    | '__root__'
    | '/'
    | '/drill'
    | '/grammar'
    | '/idioms'
    | '/phrasal'
    | '/placement'
    | '/pronunciation'
    | '/reading'
    | '/review'
    | '/vocabulary'
    | '/writing'
    | '/roadmap/$level'
    | '/roadmap/'
    | '/roadmap/$level/$lessonId'
    | '/roadmap/$level/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrillRoute: typeof DrillRoute
  GrammarRoute: typeof GrammarRoute
  IdiomsRoute: typeof IdiomsRoute
  PhrasalRoute: typeof PhrasalRoute
  PlacementRoute: typeof PlacementRoute
  PronunciationRoute: typeof PronunciationRoute
  ReadingRoute: typeof ReadingRoute
  ReviewRoute: typeof ReviewRoute
  VocabularyRoute: typeof VocabularyRoute
  WritingRoute: typeof WritingRoute
  RoadmapLevelRouteRoute: typeof RoadmapLevelRouteRouteWithChildren
  RoadmapIndexRoute: typeof RoadmapIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation': {
      id: '/pronunciation'
      path: '/pronunciation'
      fullPath: '/pronunciation'
      preLoaderRoute: typeof PronunciationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phrasal': {
      id: '/phrasal'
      path: '/phrasal'
      fullPath: '/phrasal'
      preLoaderRoute: typeof PhrasalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idioms': {
      id: '/idioms'
      path: '/idioms'
      fullPath: '/idioms'
      preLoaderRoute: typeof IdiomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/': {
      id: '/roadmap/'
      path: '/roadmap'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof RoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/$level': {
      id: '/roadmap/$level'
      path: '/roadmap/$level'
      fullPath: '/roadmap/$level'
      preLoaderRoute: typeof RoadmapLevelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/$level/': {
      id: '/roadmap/$level/'
      path: '/'
      fullPath: '/roadmap/$level/'
      preLoaderRoute: typeof RoadmapLevelIndexRouteImport
      parentRoute: typeof RoadmapLevelRouteRoute
    }
    '/roadmap/$level/$lessonId': {
      id: '/roadmap/$level/$lessonId'
      path: '/$lessonId'
      fullPath: '/roadmap/$level/$lessonId'
      preLoaderRoute: typeof RoadmapLevelLessonIdRouteImport
      parentRoute: typeof RoadmapLevelRouteRoute
    }
  }
}

interface RoadmapLevelRouteRouteChildren {
  RoadmapLevelLessonIdRoute: typeof RoadmapLevelLessonIdRoute
  RoadmapLevelIndexRoute: typeof RoadmapLevelIndexRoute
}

const RoadmapLevelRouteRouteChildren: RoadmapLevelRouteRouteChildren = {
  RoadmapLevelLessonIdRoute: RoadmapLevelLessonIdRoute,
  RoadmapLevelIndexRoute: RoadmapLevelIndexRoute,
}

const RoadmapLevelRouteRouteWithChildren =
  RoadmapLevelRouteRoute._addFileChildren(RoadmapLevelRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrillRoute: DrillRoute,
  GrammarRoute: GrammarRoute,
  IdiomsRoute: IdiomsRoute,
  PhrasalRoute: PhrasalRoute,
  PlacementRoute: PlacementRoute,
  PronunciationRoute: PronunciationRoute,
  ReadingRoute: ReadingRoute,
  ReviewRoute: ReviewRoute,
  VocabularyRoute: VocabularyRoute,
  WritingRoute: WritingRoute,
  RoadmapLevelRouteRoute: RoadmapLevelRouteRouteWithChildren,
  RoadmapIndexRoute: RoadmapIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
